export enum LexerToken {
  Identifier = "Identifier",
  StartStatement = "StartStatement",
  EndStatement = "EndStatement",
  GreaterThan = "GreaterThan",
  LessThan = "LessThan",
  Equal = "Equal",
  And = "And",
  Or = "Or",
  In = "In",
  True = "True",
  False = "False",
  Null = "Null",
  WhiteSpace = "WhiteSpace",
  NumberLiteral = "NumberLiteral",
}
